export const menus = [
  {
    id: 0,
    title: "Dashboard",
    path: "",
    roles: ["admin", "karyawan"],
    icon: "HomeIcon",
    component: "Dashboard",
  },
  {
    id: 1,
    title: "Pengajuan Pinjaman",
    path: "karyawan/pinjaman",
    roles: ["karyawan"],
    icon: "ClipboardDocumentListIcon",
    component: "karyawan/FormPengajuanPinjaman",
  },
  {
    id: 2,
    title: "Daftar Pinjaman",
    path: "karyawan/daftar_pinjaman",
    roles: ["karyawan"],
    icon: "ClipboardDocumentListIcon",
    component: "karyawan/FormDaftarPinjaman",
  },
  {
    id: 3,
    title: "Daftar Simpanan",
    path: "karyawan/daftar_simpanan",
    roles: ["karyawan"],
    icon: "CurrencyDollarIcon",
    component: "karyawan/FormDaftarSimpanan",
  },
  {
    id: 10,
    title: "Data Pinjaman",
    path: "admin/data_pinjaman",
    roles: ["admin"],
    icon: "ClipboardDocumentListIcon",
    component: "admin/FormDataPinjaman",
  },
  {
    id: 11,
    title: "Data Pelunasan",
    path: "admin/data_pelunasan",
    roles: ["admin"],
    icon: "CurrencyDollarIcon",
    component: "admin/FormDataPelunasan",
  },
  {
    id: 12,
    title: "Daftar Simpanan",
    path: "admin/daftar_simpanan",
    roles: ["admin"],
    icon: "CurrencyDollarIcon",
    component: "admin/FormDaftarSimpanan",
  },
];
